name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/awstest:latest .

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu
          if [ ! -d "awstest" ]; then
            git clone https://github.com/OH-GITAEK/awstest.git
          else
            cd awstest
            git pull origin main
          fi
          cd /home/ubuntu/awstest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/awstest:latest
          sudo docker-compose down
          sudo docker-compose up --build -d
